server:
  port: 8001

security:
  jwt:
    token:
      secret-key: secret
      expire-length: 3600000

mock:
  users:
    - id: 1
      username: user
      password: 123456
      roles:
        - ROLE_USER
        - ROLE_ADMIN
