server:
  port: 8001

security:
  jwt:
    token:
      secret-key: 12345678901234567890123456789012
      expire-length: 3600000

mock:
  users:
    - id: 1
      username: user
      password: 123456
      roles:
        - ROLE_USER
        - ROLE_ADMIN

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    root: info
    com.noisyle: debug