
package com.noisyle.demo.jws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://server.jws.demo.noisyle.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.noisyle.demo.jws.server.HelloResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.jws.demo.noisyle.com/Hello/sayHelloRequest", output = "http://server.jws.demo.noisyle.com/Hello/sayHelloResponse")
    public HelloResponse sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        HelloRequest arg0);

}
